# Imprime resultados:
print('Resumen, impresión de resultados:') 
print()
print('######################')
print('Corrientes nominales')
print('######################')
print('IN1 = %.2f A'%IN1)
print('IN2 = %.2f A'%IN2)
print('a = %.2f'%a)
print('##################')
print('Vacío:')
print('##################')
print('phi_o = %.2f°'%np.rad2deg(phi_o))
print('Ip = %.2f A'%Ip)
print('Im = %.2f A'%Im)
print('Secundario (BT):        Primario (AT):')
print('Rp2 = %.2f Ohm   |   Rp1 = %.2f Ohm'%(Rp2,Rp1))
print('Xm2 = %.2f Ohm   |   Xm1 = %.2f Ohm'%(Xm2,Xm1))
print('##################')
print('Cortocircuito:')
print('##################')
print('phi_cc = %.2f°'%np.rad2deg(phi_cc))
print('|Zeq1| = %.2f Ohm  |  |Zeq2| = %.2f Ohm'%(Zeq1,Zeq2))
print('Primario (AT):     |  Secundario (BT):')
print('Req1 = %.3f Ohm   |   Req2= %.3f Ohm'%(Req1,Req2))
print('Xeq1 = %.3f Ohm   |   Xeq2 = %.3f Ohm'%(Xeq1,Xeq2))
print('############')
print('Rendimiento:')
print('############')
print('phi_fp = %.2f°'%np.rad2deg(phi_fp))
print('Pcu = %.2f Ohm'%Pcu)
print('V2 = %.2f V'%V2)
print('n = %.4f'%n)
print('###################')
print('Rendimiento máximo:')
print('###################')
print('phi_max = %.2f°'%np.rad2deg(phi_max))
print('I2_nmax = %.2f A'%I2_nmax)
print('V2_nmax = %.2f V'%V2_nmax)
print('n_max = %.4f'%n_max)